name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      EC2_NAME: ${{secrets.RUST_FLIGHT_TRACKER_EC2_NAME}}
      SSH_PRIVATE_KEY: ${{secrets.RUST_FLIGHT_TRACKER_SSH_PRIVATE_KEY}}


    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        run: docker build -t $DOCKER_USERNAME/rust_flight_tracker:latest .
      
      - name: Push to Dockerhub
        run: docker push $DOCKER_USERNAME/rust_flight_tracker:latest
      
      - name: Deploy to EC2
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key.pem

          chmod 400 ssh_private_key.pem

          ssh -i ssh_private_key.pem $EC2_NAME << EOF

          sudo docker pull $DOCKER_USERNAME/rust_flight_tracker:latest

          sudo docker stop rust_flight_tracker_container || true

          sudo docker rm rust_flight_tracker_container || true
          
          sudo docker run -d \
            --env-file /home/ubuntu/.env \
            -p 80:3000 \
            --name rust_flight_tracker_container \
            $DOCKER_USERNAME/rust_flight_tracker:latest

          EOF

